name: jp.co.tabocom.tsplugin.infocopy.InfoCopyPlugin
version: 1.0.1
class:
  lifecycle: null
  context:
    submenus: null
    actions: |
      jp.co.tabocom.tsplugin.infocopy.InfoCopyAction
  bulkaction: null
  preferencepage: null
  dndaction: null
