name: jp.co.tabocom.tsplugin.infocopy.InfoCopyPlugin
lifecycle: null
context:
  submenu: null
  actions: |
    jp.co.tabocom.tsplugin.infocopy.InfoCopyAction
bulkaction: null
preferencepage: null
dndaction: null
